baseURL = "http://cloud9-hugo-wilson.s3-website-us-east-2.amazonaws.com"
languageCode = "en-us"
title = "My New Hugo Sit via AWS Cloud9"
theme = "ananke"

[[deployment.targets]]
# An arbitrary name for this target.
name = "awsbucket"
URL = "s3://cloud9-hugo-wilson/?region=us-east-2" #your bucket here
